nano /root/.bashrc 
ping goole.com
nano /root/.bashrc 
php -v
nano /root/.bashrc 
nano wisanggeni_nginx.sh
nano /root/.bashrc 
bash wisanggeni_nginx.sh 
nano apache_wisanggeni.sh
bash apache_wisanggeni.sh 
nano apache_wisanggeni.sh
nano wisanggeni_nginx.sh 
